### ISSUE TITLE
It is Very Bad

### ISSUE THREAD

**Issue by ModirGithub** [SpongeBobSun/KnobView#1]
Dont instal

**Comment by SpongeBobSun** [comment]
One thing is, I wrote this shit 10 month ago. Actually I didn't wrote this on purpose. As I said in the readme file, this is `forked` from another project. By forked I mean stripped. 

Another thing is, I don't give a fuck about what you say. Screw you. I may update this lib or not. That's depends on am I in a good mood or not. `I do it because I want to, not to stay in the game.`

The last thing is, could you please run a fucking spell check before you post something stupid on internet? Such a tool.
